# Generated by Django 5.2.7 on 2025-10-23 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('letter', '0002_alter_letter_topic_letter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время старта')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'создана'), ('launched', 'отправлена'), ('completed', 'завершена')], default='created', max_length=9, verbose_name='Статус')),
                ('clients', models.ManyToManyField(related_name='client', to='clients.client')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='letter.letter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['owner'],
            },
        ),
    ]
