# Generated by Django 5.2.7 on 2025-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name_mailing',
            field=models.CharField(default='default', max_length=150, unique=True, verbose_name='Название рассылки'),
            preserve_default=False,
        ),
    ]
