# Generated by Django 5.2.7 on 2025-10-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('mailing', '0003_alter_mailing_options_alter_mailing_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='clients.client', verbose_name='Получатель'),
            preserve_default=False,
        ),
    ]
