# Generated by Django 5.2.7 on 2025-10-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_attempt_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность'),
        ),
    ]
