# Generated by Django 5.2.7 on 2025-10-22 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_letter', models.CharField(help_text='Введите тему сообщения', max_length=100, verbose_name='Тема сообщения')),
                ('body_letter', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
