# Generated by Django 5.2.7 on 2025-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='topic_letter',
            field=models.CharField(help_text='Введите тему сообщения', max_length=100, unique=True, verbose_name='Тема сообщения'),
        ),
    ]
