# Generated by Django 5.2.7 on 2025-10-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность'),
        ),
    ]
